services:
   mysql-server:
     image: mysql:8.0
     container_name: zabbix-proxy-mysql
     restart: unless-stopped
     environment:
       MYSQL_DATABASE: zabbix_proxy
       MYSQL_USER: zabbix
       MYSQL_PASSWORD: ${DB_ZABBIX_USER_PASSWORD}
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
     command:
       - mysqld
       - --character-set-server=utf8mb4
       - --collation-server=utf8mb4_bin
       - --default-authentication-plugin=mysql_native_password
     volumes:
       - mysql-data:/var/lib/mysql
     networks:
       - zabbix-net
     healthcheck:
       test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "zabbix", "-p${DB_ZABBIX_USER_PASSWORD}"]
       interval: 10s
       timeout: 5s
       retries: 5
       start_period: 30s
     logging:
       driver: "json-file"
       options:
         max-size: "10m"
         max-file: "3"

   zabbix-proxy:
     image: zabbix/zabbix-proxy-mysql:ubuntu-7.0.19
     container_name: zabbix-proxy
     restart: unless-stopped
     environment:
       DB_SERVER_HOST: mysql-server
       MYSQL_DATABASE: zabbix_proxy
       MYSQL_USER: zabbix
       MYSQL_PASSWORD: ${DB_ZABBIX_USER_PASSWORD}
       ZBX_SERVER_HOST: entitledosprey.zabbix.cloud
       ZBX_SERVER_PORT: 10051
       ZBX_HOSTNAME: docker-proxy
       ZBX_PROXYMODE: 0
       ZBX_LOGLEVEL: "3"
     depends_on:
       mysql-server:
         condition: service_healthy
     networks:
       - zabbix-net
     logging:
       driver: "json-file"
       options:
         max-size: "10m"
         max-file: "3"

volumes:
  mysql-data:
    driver: local

networks:
  zabbix-net:
    driver: bridge
